#ifndef ALDA_DETAIL_EXTERNAL_CLASS_SYMBOL_HPP_INCLUDED
#define ALDA_DETAIL_EXTERNAL_CLASS_SYMBOL_HPP_INCLUDED

#if defined(ALDA_EXTERNAL_INSTANTIATION)
#	include <fcppt/class_symbol.hpp>
#	define ALDA_DETAIL_EXTERNAL_CLASS_SYMBOL FCPPT_CLASS_SYMBOL
#else
#	define ALDA_DETAIL_EXTERNAL_CLASS_SYMBOL
#endif

#endif
